project-koku/koku-daily

kokudaily/reports.py
kokudaily/sql/incomplete_manifests.sql

Adds a new report to show manifests that have not successfully processed.

Add an incomplete manifest report

---

.gitignore
kokudaily/reports.py

Fix missing comma in reports.py

Fix missing comma

---

kokudaily/sql/orphaned_providers.sql

* Remove multiple entries for the same provider for better debugging.

Group orphaned providers by provider UUID and customer ID.

---

kokudaily/reports.py
kokudaily/sql/active_providers.sql
kokudaily/sql/count_active_providers.sql

* Capture a count of active providers
* Capture a table of data on active providers

Capture active providers in metric and email.

---

kokudaily/sql/count_incomplete_manifests.sql

Update the count incomplete manifest query due to schema updates.

Update the count incomplete manifest query.

---

kokudaily/sql/active_providers.sql
kokudaily/sql/count_active_providers.sql
kokudaily/sql/count_stale_providers.sql
kokudaily/sql/stale_providers.sql

Merge latest koku-daily changes into stable.

Rc 2020.08.30

---

kokudaily/reports.py
kokudaily/sql/active_providers.sql
kokudaily/sql/count_active_providers.sql
kokudaily/sql/count_stale_providers.sql
kokudaily/sql/stale_providers.sql

Change for temp table to common table expression.

Fix no rows in resultset error.

---

kokudaily/reports.py
kokudaily/sql/active_providers.sql
kokudaily/sql/count_active_providers.sql
kokudaily/sql/count_stale_providers.sql
kokudaily/sql/stale_providers.sql

Rc 2020.09.03

---

kokudaily/engine.py

Check for empty cert file

---

kokudaily/engine.py
kokudaily/reports.py
kokudaily/sql/active_providers.sql
kokudaily/sql/count_active_providers.sql
kokudaily/sql/count_stale_providers.sql
kokudaily/sql/stale_providers.sql

Stable release.
Changelog:
- cert handling bugfixes
- enable listening on addresses beyond localhost
- openshift template updates

Release to stable, 13-Oct-2020

---

.gitignore
app.py
kokudaily/config.py
openshift/example.parameters.properties
openshift/koku-daily.yaml

This releases URL prefix support to stable.

Release to stable, 19-Oct-2020

---

Pipfile
Pipfile.lock
kokudaily/reports.py
kokudaily/sql/cust_size_report.sql
kokudaily/sql/cust_size_report_setup.sql
kokudaily/sql/cust_size_report_teardown.sql

[COST-638](https://issues.redhat.com/browse/COST-638)
Added a query to satisfy the needs of a customer size report.
This required that a setup and teardown step be added to `run_reports`. This was needed because the `cust_size_report` will crawl all schemata for OCP providers looking for information.
Also, cleaned up a little so that queries did not need to be executed twice.
This was engineered to be run via the daily job. Executing this via the UI will fail.

Cost 638 customer size query

---

kokudaily/reports.py
kokudaily/sql/count_customers_by_setup_state.sql
kokudaily/sql/count_providers_by_type.sql
kokudaily/sql/list_filtered_accounts_with_new_source_last_7_days.sql

These will make reporting weekly metrics a little easier.

Add 3 new reports for weekly status report

---

kokudaily/reports.py
kokudaily/sql/count_customers_by_setup_state.sql
kokudaily/sql/count_filtered_users_by_account.sql
kokudaily/sql/count_filtered_users_by_domain.sql
kokudaily/sql/count_providers_by_filtered_account.sql
kokudaily/sql/count_providers_by_setup_state_and_filtered_account.sql
kokudaily/sql/count_providers_by_type.sql
kokudaily/sql/list_filtered_accounts.sql
kokudaily/sql/list_filtered_accounts_with_new_source_last_7_days.sql

- Reconciling counts in certain reports where an account has users with multiple email domains. 
- Fixing greater than / less than bug

Update domain in reports

---

kokudaily/sql/active_providers.sql

Add cluster id to the active source report.

Add source id to the active providers report

---

Dockerfile
Makefile
build_deploy.sh
pr_check.sh

* Create Dockerfile to build image
* Add app-interface build and pr check scripts
https://issues.redhat.com/browse/COST-1399

Create Dockerfile and app-interface scripts

---

kokudaily/sql/count_filtered_users.sql

Add a count of users that are associated with active customers (those that have sources).

Update user count SQL

---

kokudaily/reports.py
kokudaily/sql/count_airgapped_clusters.sql
kokudaily/sql/count_certified_clusters.sql
kokudaily/sql/count_community_clusters.sql
kokudaily/sql/count_connected_clusters.sql
kokudaily/sql/count_errored_clusters.sql

Add reports around operator info such as: 
- connected clusters
- airgapped clusters 
- clusters with errors
- clusters using certified operator
- clusters using the community operator

Initial SQL & reports for operator information

---

deploy/clowdapp.yaml

This PR let's us override `EMAIL_GROUPS` through app-interface.

make `EMAIL_GROUPS` a parameter in the clowdapp template

---

deploy/clowdapp.yaml

* Update objectstore
* Update schedule.

Fix the objectstore association.

---

Dockerfile
Pipfile
Pipfile.lock
deploy/clowdapp.yaml

- use ubi8/ubi-minimal base image
- upgrade dependencies

switch to ubi-minimal dockerfile and dependency update

---

deploy/clowdapp.yaml

Remove koku-daily-prom job
Not being used by current alerting

Remove koku-daily-prom

---

kokudaily/sql/cust_node_report_setup.sql

Remove reference of an old table in favor of the new table name.

Reference daily summary table for cust_node_report.

---

kokudaily/sql/key_metrics/cust_cloud_costs_data_setup.sql
kokudaily/sql/key_metrics/cust_openshift_costs_data_setup.sql
kokudaily/sql/key_metrics/cust_openshift_infra_data_setup.sql

* Exclude `acct6193296` (cost-demo) and `acct6089719` (insights-qa) from key metrics collection.

key metrics exclusions

---

.dockerignore
build_deploy.sh

* create tmp dir for build-deploy
* add .dockerignore to exclude what we dont need

[COST-4896] create tmp dir for build-deploy

---

kokudaily/sql/key_metrics/cust_cloud_costs_data.sql
kokudaily/sql/key_metrics/cust_openshift_costs_data.sql
kokudaily/sql/key_metrics/cust_openshift_infra_data.sql

* use md5 to hash the schema name so that it's clear which line items are correlated

hash schema name

---

renovate.json

This will reduce the frequency of Konflux PRs.
Validate the expression with https://codepen.io/rationaltiger24/full/ZExQEgK
[Renovate configuration options](https://docs.renovatebot.com/configuration-options/#schedule)

[COST-5429] Add Renovate config

---

deploy/clowdapp.yaml

Switch to using image built by Konflux.

Change container image

---

.tekton/koku-daily-pull-request.yaml
.tekton/koku-daily-push.yaml

Remove deprecated check.
[Migration](https://raw.githubusercontent.com/konflux-ci/build-definitions/main/task/sbom-json-check/0.2/MIGRATION.md).

Remove deprecated sbom-json-check
